server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wintertea-user?useUnicode=true&characterEncoding=UTF8&useSSL=true
    username: root
    password: 1qaz@WSX
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT now()
      connection-properties: characterEncoding=utf8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wintertea.service.user.services.entity


mapper:
  not-empty: false
  identity: MYSQL
  mappers:
    - com.wintertea.commons.mapper.BaseMapper

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  level:
    com.wintertea.service.user.services.dao : debug
  config: classpath:logback-spring.xml